.github/ISSUE_TEMPLATE/story.md

Create issue template

---

backend/.gitignore
backend/package-lock.json
backend/package.json
backend/server.js
client/package-lock.json
client/package.json
client/src/App.js
client/src/App.test.js
client/src/pages/Landing/Landing.js

- Added client routing using react-router-dom and connect newly created landing page to route.

client routing and landing page

---

client/src/App.js
client/src/App.test.js

- Created blank test for testing App.js which is automatically integrated with the CI.
- Addresses issue #51

Create blank test

---

client/src/pages/Contact/Contact.js
client/src/pages/ErrorPage/ErrorPage.js

- Created 404 error page and contact page that is demonstrated in a [video](https://youtu.be/hCiRHA73EVw).
- Addresses issue #53

Add 404 error page and contact page

---

.github/ISSUE_TEMPLATE/story.md

- Fixed the issue template to have a story points field as per the requirements of the project.

Add story points bullet to the issues template

---

client/src/App.js
client/src/components/Navbar/Navbar.js

- Create initial code/files for navbar.
- Addresses issue #60

Create navbar files and import into app.js

---

client/src/App.js
client/src/pages/Landing/Landing.js

- Added page routes for contact and error page.

Add page routes

---

backend/controllers/auth.js
backend/routes/auth.js
backend/server.js

- This change allows the backend express.js server to connect to MongoDB Atlas and also implements a dummy route and controller.
- Addresses issue #63

Connect backend to MongoDB Atlas

---

backend/controllers/auth.js
backend/models/user.js
backend/routes/auth.js
backend/server.js
backend/validators/auth.js
backend/validators/index.js

- User can now register for an account using first name, last name, email, and password.
- User can login to registered account with email and password.
- All know error cases are caught and handled properly.
- Addresses issue #31 & #33

User Registration and Signin

---

backend/README.md
backend/controllers/profile.js
backend/routes/profile.js

- Documents the most recent backend changes.
- Updated profile Create/Update API endpoint to be more descriptive.
- Addresses PR #68 #66

Document backend REST API endpoints list

---

backend/controllers/auth.js
backend/controllers/profile.js
backend/models/Profile.js
backend/models/user.js
backend/routes/auth.js
backend/validators/auth.js
backend/validators/profile.js

- Moved first name and last name to profile instead of user document.
- Compresses validation functions to one validation function for authentication.
- Separates user credential info from user profile info.
- Addresses issue #40

Schema design update for User and Profile

---

client/src/App.css
client/src/components/HomepageImage.js
client/src/pages/Landing/Landing.js

- Very basic landing page.
-   Addresses issue #49

Add landing page v1

---

backend/controllers/chirp.js
backend/models/Chirp.js
backend/routes/chirp.js
backend/server.js

- This starts the chirp functionality in the backend.
- Addresses issue #70 #35

Chirp schema and DB design update

---

client/src/App.css
client/src/components/HomepageImage.js
client/src/pages/Landing/Landing.js

- Made adjustments to the landing page to look slightly better.
- Addresses issue #72

Fix typo in the heading and heading and logo are now bigger.

---

client/package-lock.json
client/package.json
client/src/App.js
client/src/components/LoginAndReg/Login.js
client/src/components/LoginAndReg/Registration.js
client/src/pages/AuthPage/AuthPage.js
client/src/pages/Landing/Landing.js

- Implement user login and registration on the client.
- Addresses issue #73

Implement login in reg with fronend and backend

---

backend/.eslintrc.js
backend/package-lock.json
backend/package.json
client/.eslintrc.js
client/package-lock.json
client/package.json

- Add eslint configuration files to backend and frontend.
- Each configuration file is a little different because of the environment the JavaScript runs in (browser, vs node).
- Addresses PR #77

Add ESLint configuration

---

client/src/App.css
client/src/App.js
client/src/App.test.js
client/src/components/Navigation/Navigation.js
client/src/index.js
client/src/lib/api/auth.js
client/src/pages/Landing/Landing.js
client/src/pages/Landing/Landing.test.js
client/src/pages/Profile/Profile.js

- Use React Hook to automatically update navigation component based on whether user is logged in or not.
- Later we will add api calls to verify the authentication token.
- Addresses issue #19

Conditional navbar

---

backend/controllers/auth.js
client/src/App.js
client/src/components/CreateProfile/CreateProfile.css
client/src/components/CreateProfile/CreateProfile.js
client/src/components/LoginAndReg/Login.js
client/src/pages/AuthPage/AuthPage.js

- Redirect new user login to create profile page, then to profile page.
- If user isn't new redirect to home page after login.
- Addresses issue #38

Redirect new users to create profile page after login

---

client/src/components/profileCard/profileCard.js

- Create skeleton for profile information
- Addresses issue #80

Update profile pic

---

backend/controllers/profile.js
backend/routes/profile.js
client/src/components/profileCard/profileCard.js
client/src/pages/Profile/Profile.js

- Connects backend and frontend profile page.
- Redirects to create profile page if user doesnt have profile setup yet.
- Addresses issue #40

Connect profile page to backend and update state in frontend

---

client/src/App.js
client/src/components/Navigation/Navigation.js
client/src/lib/api/auth.js

- Added Logout function to lib/Auth.js.  Added handleLogout to App.js and passed it as prop to NavBar.

Logout Functionality

---

client/src/components/Chirp/Chirp.js

- Implements liking feature on client side.
_Note: This is partially implemented since this is minimal change and is only client side._
- Addresses issue #44

Like chirp client

---

backend/controllers/chirp.js
backend/models/Chirp.js
backend/routes/chirp.js

- Implements liking feature on backend side.
_Note: Client and Backend are not tied in together yet. Another PR will combine the two to finish this feature._
- Addresses issue #44

Like chirp backend

---

client/src/App.js

- Added isAuthed={isAuthed} to profile route.
- Addresses issue #97

Profile routing bug fix

---

backend/controllers/chirp.js
client/src/components/Chirp/Chirp.js
client/src/components/LoginAndReg/Login.js
client/src/pages/Feed/Feed.js

- Like a chirp completion.
- Backend/Client are tied together, making users able to like a chirp.
- Addresses issue #44 #45

Like chirp

---

client/package-lock.json
client/package.json
client/src/actions/index.js
client/src/actions/types.js
client/src/index.js
client/src/reducers/index.js

- Sets up Redux, React-Redux, Redux-Thunk for better application state storage/handling.
- This setup will allow the fix of bug addressed bellow, along with fixing future issues in state management.
- Addresses issue #99

Redux setup for better state handling

---

backend/controllers/auth.js
backend/controllers/chirp.js
backend/controllers/profile.js
client/src/actions/index.js
client/src/components/AlertMessage/AlertMessage.js
client/src/components/LoginAndReg/Login.js
client/src/components/LoginAndReg/Registration.js
client/src/lib/hooks/useAuthStatus.js
client/src/reducers/authReducer.js

- Fixes user registration.
- Handles registratin/login errors and displays to user.
- Addresses issue #108

Registration fix

---

client/src/pages/Landing/Landing.js

- Fixes landing page styling issue.
- Addresses issue #106

Fix landing page style that was broken by previous commit

---

client/src/App.js
client/src/components/FullPageSpinner/FullPageSpinner.js

- Still a work in progress; cannot figure out how to center it in the middle of the page. I have it centered, but it is at top. Any thoughts @JustinASmith? (see image below)
- Also I might have another bug in the landingpage. Is this showing up like this for everyone else too?
- Addresses issue #104

Add fullpagespinner

---

backend/controllers/chirp.js
client/src/App.js
client/src/actions/index.js
client/src/actions/types.js
client/src/components/AlertMessage/AlertMessage.js
client/src/components/Chirp/Chirp.js
client/src/components/CreateProfile/CreateProfile.js
client/src/lib/checkTokenExiryMiddleware.js
client/src/lib/hooks/useStatus.js
client/src/pages/AuthPage/AuthPage.js
client/src/pages/Feed/Feed.js
client/src/pages/Profile/Profile.js
client/src/reducers/authReducer.js
client/src/reducers/chirpReducer.js
client/src/reducers/index.js
client/src/reducers/networkReducer.js

- Integrates all features into new Redux actions/reducers.
- Fixes all profile features.
- Fixes all chirp features.
- Handles all known edge cases.
_Note: Minor performance issues, and less than perfect user experience when liking chirps_
- Addresses issue #103

Chirp/Profile features fix/enhancement

---

client/src/components/Chirp/Chirp.js

- Adds hover effects to chirp like/rechirp buttons. 
- Addresses issue #111

Chirpr button hover

---

backend/controllers/chirp.js
backend/models/Chirp.js
backend/routes/chirp.js
client/src/actions/index.js
client/src/actions/types.js
client/src/components/Chirp/Chirp.js
client/src/pages/Feed/Feed.js
client/src/reducers/chirpReducer.js

- Implements ReChirp feature.
- Handles user clicks on ReChirp button through action creators.
- Stores ReChirps in database.
- Handles state of ReChirps: count, if user rechirped something, and if ReChirp was successful.
- Addresses issue #46 #47

Rechirp feature

---

client/src/components/LoginAndReg/Login.js
client/src/components/LoginAndReg/__tests__/login.js

- All tests written for user Login component.
- Handles:
- Success cases: with/without profile
- Invalid credentials
- Request error display
_Login/Registration components are 100% covered._
- Addresses issue #115

Login tests

---

client/src/components/Chirp/Chirp.js
client/src/components/Chirp/__tests__/del.js
client/src/components/Chirp/__tests__/edit.js

- WIP front end there is an error inside of the edit.js file.
- Addresses issue #(type issue number here)

Chirp components testing

---

client/src/components/Chirp/__tests__/like.js

- Same as PR #133 ; merge conflict was taking too long to resolve so creating a new PR with the same changes.

Add keiths test

---

client/src/components/ChirpInputForm/ChirpInputForm.js
client/src/components/ChirpInputForm/__tests__/createChirp.js

- Adds create chirp testing.
- Wasn't sure how to receive input from chirp box as it wasn't working for me, so I just got rid of it.
- Addresses issue #135

Create chirp component
